service: ants-score-service-java

provider:
  name: aws
  runtime: java8
  region: us-west-2
  role: arn:aws:iam::329054710135:role/lambda-kinesis-ants

package:
  artifact: build/distributions/ants-score-service-java-1.0.zip

functions:
  getPlayersScoresJava:
    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.GetPlayersScoresHandler
    events:
      - http:
          path: scores/games/{gameId}/players
          method: get

  getTeamsScoresJava:
      handler: com.tikal.fuze.antscosmashing.scoreservice.handler.GetTeamsScoresHandler
      events:
        - http:
            path: scores/games/{gameId}/teams
            method: get

  postHitTrialJava:
        handler: com.tikal.fuze.antscosmashing.scoreservice.handler.PostHitTrialHandler
        events:
          - http:
              path: hit-trials
              method: post
        environment:
            HIT: 1
            FIRST_HIT: 3
            SELF_HIT: -1
            FIRST_SELF_HIT: -3

  kinesisHitTrialEventsJava:
        handler: com.tikal.fuze.antscosmashing.scoreservice.handler.KinesisHitTrialEventsHandler
        events:
          - stream:
              arn: arn:aws:kinesis:us-west-2:329054710135:stream/Ants-Smashing-HitTrials
              batchSize: 100
              startingPosition: LATEST
        environment:
            HIT: 1
            FIRST_HIT: 3
            SELF_HIT: -1
            FIRST_SELF_HIT: -3



resources:
  Resources:
    hitTrialsStream:
      Type: 'AWS::Kinesis::Stream'
      Properties:
        Name: Ants-Smashing-HitTrials
        RetentionPeriodHours: 168
        ShardCount: 1
    playersCoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Ants-Smashing-PlayersScore
        AttributeDefinitions:
          - AttributeName: playerId
            AttributeType: N
          - AttributeName: score
            AttributeType: N
          - AttributeName: gameId
            AttributeType: N
        KeySchema:
          - AttributeName: playerId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: gameId_score_idx
            KeySchema:
              - AttributeName: gameId
                KeyType: HASH
              - AttributeName: score
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
    teamsCoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Ants-Smashing-TeamsScore
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: N
          - AttributeName: score
            AttributeType: N
          - AttributeName: gameId
            AttributeType: N
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: gameId_score_idx
            KeySchema:
              - AttributeName: gameId
                KeyType: HASH
              - AttributeName: score
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
    smashedAntsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Ants-Smashing-smashedAnts
        AttributeDefinitions:
          - AttributeName: antId
            AttributeType: S
        KeySchema:
          - AttributeName: antId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5