service: ants-score-service-java

provider:
  name: aws
  runtime: java8
  region: us-west-2
  role: arn:aws:iam::329054710135:role/lambda-kinesis-ants

package:
  artifact: ./build/distributions/ants-score-service-java-1.0.zip

functions:
  postHitTrialJava:
    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.hittrials.PostHitTrialHandler
    events:
      - http:
          path: ''
          method: post
    environment:
      HIT: 1
      FIRST_HIT: 3
      SELF_HIT: -1
      FIRST_SELF_HIT: -3

  kinesisHitTrialEventsJava:
    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.hittrials.KinesisHitTrialEventsHandler
    events:
      - stream:
          arn: arn:aws:kinesis:us-west-2:329054710135:stream/Ants-Smashing-HitTrials
          batchSize: 100
          startingPosition: LATEST
    environment:
      HIT: 1
      FIRST_HIT: 3
      SELF_HIT: -1
      FIRST_SELF_HIT: -3


plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "fuze.tikal.io"
    basePath: 'hitTrials'
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: 'regional'







#  getPlayersScoresJava:
#    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.scores.GetPlayersScoresHandler
#    events:
#      - http:
#          path: scores/games/{gameId}/players
#          method: get
#
#  getTeamsScoresJava:
#    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.scores.GetTeamsScoresHandler
#    events:
#      - http:
#          path: scores/games/{gameId}/teams
#          method: get

