service: ants-score-service-java

provider:
  name: aws
  runtime: java8
  region: us-west-2
  role: arn:aws:iam::329054710135:role/lambda-kinesis-ants

package:
  artifact: ../../../../build/distributions/ants-score-service-java-1.0.zip

functions:
  postHitTrialJava:
    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.PostHitTrialHandler
    events:
      - http:
          path: hit-trials
          method: post
    environment:
      HIT: 1
      FIRST_HIT: 3
      SELF_HIT: -1
      FIRST_SELF_HIT: -3

  kinesisHitTrialEventsJava:
    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.KinesisHitTrialEventsHandler
    events:
      - stream:
          arn: arn:aws:kinesis:us-west-2:329054710135:stream/Ants-Smashing-HitTrials
          batchSize: 100
          startingPosition: LATEST
    environment:
      HIT: 1
      FIRST_HIT: 3
      SELF_HIT: -1
      FIRST_SELF_HIT: -3







#  getPlayersScoresJava:
#    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.GetPlayersScoresHandler
#    events:
#      - http:
#          path: scores/games/{gameId}/players
#          method: get
#
#  getTeamsScoresJava:
#    handler: com.tikal.fuze.antscosmashing.scoreservice.handler.GetTeamsScoresHandler
#    events:
#      - http:
#          path: scores/games/{gameId}/teams
#          method: get

